import { ImageResponse } from "@vercel/og";
import { NextRequest } from "next/server";
import { fetchGithubData } from "@/lib/github/client";
import {
  CardData,
  ProcessedUserData,
  ProcessedRepoData,
  ProcessedOrgData,
  ContributionWeek,
} from "@/lib/github/types";

export const runtime = "edge";

// Load fonts
const interRegular = fetch(
  "https://cdn.jsdelivr.net/fontsource/fonts/inter@latest/latin-400-normal.woff",
).then((res) => res.arrayBuffer());

const interBold = fetch(
  "https://cdn.jsdelivr.net/fontsource/fonts/inter@latest/latin-700-normal.woff",
).then((res) => res.arrayBuffer());

export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url);
  const username = searchParams.get("username");
  const format = searchParams.get("format") || "png";

  if (!username) {
    return new Response("Username is required", { status: 400 });
  }

  try {
    const data = await fetchGithubData(username);
    const [regularData, boldData] = await Promise.all([
      interRegular,
      interBold,
    ]);

    const fonts = [
      {
        name: "Inter",
        data: regularData,
        style: "normal" as const,
        weight: 400 as const,
      },
      {
        name: "Inter",
        data: boldData,
        style: "normal" as const,
        weight: 700 as const,
      },
    ];

    // Note: Satori doesn't support SVG native export via ImageResponse directly in the same way,
    // but ImageResponse returns an image. If 'svg' format is requested strictly as XML,
    // we would need 'satori' package import.
    // However, keeping consistent with the previous file structure:
    return new ImageResponse(<CardTemplate data={data} />, {
      width: 1200,
      height: 630,
      fonts: fonts,
    });
  } catch (e: any) {
    console.error(e);
    return new Response(`Failed to generate image: ${e.message}`, {
      status: 500,
    });
  }
}

// --- Components ---

function CardTemplate({ data }: { data: CardData }) {
  const isRepo = data.type === "repo";
  const isOrg = data.type === "organization";

  // Background gradient from CardPreview (purple-500/20 blur)
  // We can't do exact blur, so we simulate with a dark gradient + inner glow

  return (
    <div
      style={{
        width: "100%",
        height: "100%",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        background: "#0f172a", // Slate 900 base
        color: "white",
        fontFamily: '"Inter"',
        position: "relative",
      }}
    >
      {/* Background Decor (Simulating the blur blob) */}
      <div
        style={{
          position: "absolute",
          top: "50%",
          left: "50%",
          transform: "translate(-50%, -50%)",
          width: "600px",
          height: "600px",
          backgroundImage:
            "radial-gradient(circle, rgba(168, 85, 247, 0.4) 0%, rgba(168, 85, 247, 0) 70%)",
          display: "flex",
        }}
      />

      {/* Main Card Content */}
      <div
        style={{
          display: "flex",
          flexDirection: "column",
          width: "900px",
          backgroundColor: "rgba(255, 255, 255, 0.1)", // Glass base
          border: "1px solid rgba(255, 255, 255, 0.2)",
          borderRadius: "24px",
          padding: "48px",
          boxShadow: "0 25px 50px -12px rgba(0, 0, 0, 0.5)",
        }}
      >
        {/* Header */}
        <Header data={data} />

        {/* Stats */}
        <StatsRow data={data} />

        {/* Language Bar */}
        <LanguageBar languages={data.languages} />

        {/* Contributions (Users Only) */}
        {!isRepo && "contributions" in data && (
          <ContributionGraph days={data.contributions.calendar} />
        )}

        {/* Footer */}
        <div
          style={{
            marginTop: "32px",
            paddingTop: "16px",
            borderTop: "1px solid rgba(255, 255, 255, 0.1)",
            display: "flex",
            justifyContent: "space-between",
            width: "100%",
            fontSize: "14px",
            color: "#94a3b8", // slate-400
          }}
        >
          <span>Generated by gh-card.dev</span>
          <span>{new Date().toLocaleDateString()}</span>
        </div>
      </div>
    </div>
  );
}

function Header({ data }: { data: CardData }) {
  const isRepo = data.type === "repo";
  const name = isRepo ? data.name : data.name || data.username;
  const subtext = isRepo ? `${data.owner}/${data.name}` : `@${data.username}`;
  const desc =
    "description" in data ? data.description : "bio" in data ? data.bio : null;

  return (
    <div style={{ display: "flex", width: "100%", marginBottom: "32px" }}>
      <div style={{ display: "flex", alignItems: "flex-start", gap: "24px" }}>
        {/* Avatar */}
        <div style={{ display: "flex", position: "relative" }}>
          {/* Avatar Border Gradient Substitute */}
          <div
            style={{
              position: "absolute",
              top: "-4px",
              left: "-4px",
              right: "-4px",
              bottom: "-4px",
              borderRadius: "50%",
              backgroundImage: "linear-gradient(to right, #6366f1, #a855f7)",
              opacity: 0.75,
              display: "flex",
            }}
          />
          <img
            src={data.avatarUrl}
            width="96"
            height="96"
            style={{
              borderRadius: "50%",
              border: "2px solid rgba(255,255,255,0.2)",
              position: "relative", // Bring above glow
            }}
          />
        </div>

        <div style={{ display: "flex", flexDirection: "column" }}>
          <span
            style={{
              fontSize: "36px",
              fontWeight: 700,
              color: "white",
              lineHeight: 1.1,
            }}
          >
            {name}
          </span>
          <span
            style={{ fontSize: "20px", color: "#a5b4fc", marginTop: "4px" }}
          >
            {subtext}
          </span>
          {desc && (
            <span
              style={{
                fontSize: "16px",
                color: "#cbd5e1",
                marginTop: "12px",
                maxWidth: "600px",
                lineHeight: 1.5,
                // lineClamp isn't fully supported in satori the same way, but wrapping works
                display: "flex",
              }}
            >
              {desc.length > 120 ? desc.substring(0, 120) + "..." : desc}
            </span>
          )}
        </div>
      </div>
    </div>
  );
}

function StatsRow({ data }: { data: CardData }) {
  const isRepo = data.type === "repo";
  const isOrg = data.type === "organization";

  let stats: { label: string; value: number; icon: string }[] = [];

  if (isRepo) {
    stats = [
      { label: "Stars", value: data.stars, icon: "⭐" },
      { label: "Forks", value: data.forks, icon: "🍴" },
      { label: "Watchers", value: data.watchers, icon: "👀" },
    ];
  } else if (isOrg) {
    stats = [
      { label: "Stars", value: data.totalStars, icon: "⭐" },
      { label: "Repos", value: data.totalRepos, icon: "📦" },
      { label: "Forks", value: data.totalForks, icon: "🍴" },
    ];
  } else {
    // User
    stats = [
      {
        label: "Stars",
        value: (data as ProcessedUserData).totalStars,
        icon: "⭐",
      },
      {
        label: "Commits",
        value: (data as ProcessedUserData).totalCommits,
        icon: "🔥",
      },
      {
        label: "Repos",
        value: (data as ProcessedUserData).totalRepos,
        icon: "📦",
      },
      {
        label: "Followers",
        value: (data as ProcessedUserData).followers,
        icon: "👥",
      },
    ];
  }

  return (
    <div style={{ display: "flex", gap: "16px", width: "100%" }}>
      {stats.map((stat) => (
        <StatBlock key={stat.label} {...stat} />
      ))}
    </div>
  );
}

function StatBlock({
  label,
  value,
  icon,
}: {
  label: string;
  value: number;
  icon: string;
}) {
  const formattedValue =
    value >= 1000 ? (value / 1000).toFixed(1) + "k" : value.toString();

  return (
    <div
      style={{
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        flex: 1,
        backgroundColor: "rgba(255, 255, 255, 0.05)",
        border: "1px solid rgba(255, 255, 255, 0.05)",
        borderRadius: "16px",
        padding: "20px 16px",
      }}
    >
      <span style={{ fontSize: "28px", marginBottom: "8px" }}>{icon}</span>
      <span
        style={{
          fontSize: "28px",
          fontWeight: 700,
          color: "white",
        }}
      >
        {formattedValue}
      </span>
      <span
        style={{
          fontSize: "14px",
          color: "#94a3b8",
          textTransform: "uppercase",
          letterSpacing: "1px",
          fontWeight: 500,
          marginTop: "4px",
        }}
      >
        {label}
      </span>
    </div>
  );
}

function LanguageBar({
  languages,
}: {
  languages: Array<{
    name: string;
    color: string;
    percentage: number;
  }>;
}) {
  if (!languages.length) return null;

  return (
    <div
      style={{
        display: "flex",
        flexDirection: "column",
        width: "100%",
        marginTop: "32px",
      }}
    >
      {/* Bar */}
      <div
        style={{
          display: "flex",
          width: "100%",
          height: "12px",
          borderRadius: "6px",
          overflow: "hidden",
          backgroundColor: "rgba(30, 41, 59, 0.5)", // slate-800/50
          border: "1px solid rgba(255, 255, 255, 0.1)",
        }}
      >
        {languages.map((lang, i) => (
          <div
            key={lang.name}
            style={{
              width: `${lang.percentage}%`,
              height: "100%",
              backgroundColor: lang.color,
            }}
          />
        ))}
      </div>

      {/* Legend */}
      <div
        style={{
          display: "flex",
          flexWrap: "wrap",
          gap: "16px",
          marginTop: "12px",
          justifyContent: "center",
        }}
      >
        {languages.map((lang) => (
          <div
            key={lang.name}
            style={{ display: "flex", alignItems: "center", gap: "8px" }}
          >
            <div
              style={{
                width: "8px",
                height: "8px",
                borderRadius: "50%",
                backgroundColor: lang.color,
              }}
            />
            <span
              style={{ fontSize: "14px", fontWeight: 500, color: "#cbd5e1" }}
            >
              {lang.name}
            </span>
            <span style={{ fontSize: "14px", color: "#64748b" }}>
              {lang.percentage}%
            </span>
          </div>
        ))}
      </div>
    </div>
  );
}

function ContributionGraph({ days }: { days: ContributionWeek[] }) {
  // Only show last 10 weeks same as component
  const weeks = days;

  return (
    <div
      style={{
        display: "flex",
        flexDirection: "column",
        marginTop: "32px",
        width: "100%",
      }}
    >
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "flex-end",
          marginBottom: "12px",
        }}
      >
        <span
          style={{
            fontSize: "14px",
            fontWeight: 600,
            color: "#94a3b8",
            textTransform: "uppercase",
            letterSpacing: "0.05em",
          }}
        >
          Contributions
        </span>
        <span style={{ fontSize: "14px", color: "#64748b" }}>
          Last 10 Weeks
        </span>
      </div>

      <div
        style={{ display: "flex", justifyContent: "space-between", gap: "6px" }}
      >
        {weeks.map((week, i) => (
          <div
            key={i}
            style={{ display: "flex", flexDirection: "column", gap: "5px" }}
          >
            {week.contributionDays.map((day) => (
              <div
                key={day.date}
                style={{
                  width: "12px",
                  height: "12px",
                  borderRadius: "2px",
                  backgroundColor:
                    day.contributionCount > 0
                      ? day.color
                      : "rgba(255, 255, 255, 0.05)",
                  opacity: day.contributionCount > 0 ? 0.8 : 1,
                }}
              />
            ))}
          </div>
        ))}
      </div>
    </div>
  );
}
